### ISSUE TITLE
Peer Code Review

### ISSUE THREAD

**Issue by Mckenziematt** [lukestageberg/Fastball_Velocity#1]
---
layout: page
title: Code Review
---

### Purpose
* Is the purpose of the project is clear?
Yes

* Is it clear what each file in the project is intened for?
Two files, one can be deleted because it didn't have anything in it

* It is clear how the various files interact?
NA
* Is it clear what the purpose if of specific sections of code?
Kind of. I would be descriptions for each section of code, describing what you're doing 
I would describe what your pvalue means for your project and what you found to be significant and not significant

* How well commented is the code on a scale of 1(no comments) to 10(very well commented).
1 no comments (but you said you were working on this)

* How can the purposes of the project and files be improved?
just add comments and then I think you said you also were gonna work on some code before it due. 
### Organization

* Is the project organized such that you can intuit where the data, 
scripts, and output files are stored? 
Yes

* Approximately how much time did it take you to understand the work flow
in the project?
Just because there are no comments that made it more difficult. However, the flow of the code was easy for me to work through. So in the comments describe what variables you are comparing and what they describe from the graphs.

* How well defined are code chunks in the project? 
Like I said, you are loading comments later this week. So I think just explain what each line means and what your variables are in your code chunk. 

* How can organization be improved?
Very organized just needs some comments

### Functionality 

* Does the code appear to advance the purpose of the project?
The purpose of the project was to find predictor variables for fastball velocity. So these models do well at explaining what variables contribute to fastball velocity.

* Do the existing components of the project appear to function?
YES

* How can the author improve functionality of code?
Just add comments. maybe he should try doing a correlation matrix. 

## Specific File Comments
* README.md
    - I would maybe post a dictionary. Explaining what your baseball terms are. For the average person to look at this they might get really confused. But it would be a lot easier to understand if you defined them.

**Comment by lukestageberg** [comment]
These were attended to in commit 86d2a9d
